" No space after (=) allowed
set guifont=Courier\ New\:h12 " Font and size
set encoding=utf-8 " Encoding inside vim
set fileencoding=utf-8 " File buffer encoding by default
set visualbell " No error beep. Just flash screen

syntax enable " Set syntax highlighting on
colorscheme molokai " Color scheme. Download it

set listchars=space:\ ,tab:>\ ,trail:.
set list " Show whitespace chars

set history=200 " Number of ':' commands in history

set incsearch " Search while entering search pattern
set smartcase " Smart case for search
set timeoutlen=10

set smartindent " Insert smart indent automatically

" Do not lose indent if line is empty
nnoremap O O<SPACE><BS>
nnoremap o o<SPACE><BS>
inoremap <CR> <SPACE><BS><CR>
inoremap <ESC> <SPACE><BS><ESC>

set paste " Use paste mode for terminals
set nowrap " Use no word wrap
set tabstop=2 " Spaces in one tab
set shiftwidth=0 " Use indent like tabstop
set softtabstop=0 noexpandtab
set wildmode=list,full

set number " Show line numbers
set showcmd
set hlsearch
set laststatus=2

function! GetLineBr()
	if &fileformat == 'dos'
		return '\r\n'
	elseif &fileformat == 'unix'
		return '\r'
	elseif &fileformat == 'mac'
		return '\n'
	endif
endfunction

set statusline=%<%F " Full file path
set statusline+=\ %m
set statusline+=%r
set statusline+=%h
set statusline+=%w
set statusline+=%q
set statusline+=%k
set statusline+=%a
set statusline+=%=
set statusline+=%p%% " Current percent of file
set statusline+=\ (%l/%L) " (current line / all lines )
set statusline+=\ [%{&fileencoding==''?'bin':&fileencoding}] " File encoding
set statusline+=\ [%{&fileformat}:%{GetLineBr()}] " File format and EOL
set statusline+=\ 0x%-5B " Hex of current char

set noundofile
